version: 2

sources:
  - name: staging
    database:
      philly-crime-incidents
      # For postgres:
      #database: production
    schema:
      philly_crime_data

      # loaded_at_field: record_loaded_at
    tables:
      - name: 2006-2023_crime_data

models:
  - name: stg_2006-2023_crime_data
    description: "Part 1 & Part 2 Crime Incidents from the Police Department's INCT system with generalized UCR codes and addresses rounded to the hundred block. These counts may not coincide exactly with data that is submitted to the Uniformed Crime Reporting (UCR) system."
    columns:
      - name: crime_id
        data_type: string
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn

      - name: objectid
        data_type: int64
        description: ""

      - name: police_key
        data_type: int64
        description: " The unique identifier of the crime that consists of Year + District + Unique ID. "
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn

      - name: police_district
        data_type: int64
        description: " 	A two character field that names the District boundary. "
        tests:
          - not_null:
              severity: warn

      - name: psa
        data_type: string
        description: " 	A single character field that names the Police Service Area boundary. "

      - name: dispatch_date_time
        data_type: timestamp
        description: " The date and time that the officer was dispatched to the scene."

      - name: dispatch_date
        data_type: timestamp
        description: "Dispatch date formatted as a string, but converted to a timestamp. "
        tests:
          - not_null:
              severity: warn

      - name: dispatch_time
        data_type: timestamp
        description: "Dispatch time formatted as a string, but converted to a timestamp. "

      - name: hour
        data_type: int64
        description: " The generalized hour of the dispatched time. "
        tests:
          - not_null:
              severity: warn

      - name: day_of_week
        data_type: string
        description: "The day of the week on which the incident was reported."
        tests:
          - not_null:
              severity: warn

      - name: month
        data_type: int64
        description: "The month of the year in which the incident was reported."
        tests:
          - not_null:
              severity: warn

      - name: quarter
        data_type: int64
        description: "The quarter of the year in which the incident was reported."
        tests:
          - not_null:
              severity: warn

      - name: ucr_code
        data_type: int64
        description: "The rounded crime code, i.e. 614 to 600."
        tests:
          - not_null:
              severity: warn

      - name: crime_type
        data_type: string
        description: "The generalized text for the crime code."
        tests:
          - not_null:
              severity: warn

      - name: location_block
        data_type: int64
        description: "Street address of the block where the crime occurred."
        tests:
          - not_null:
              severity: warn

      - name: point_x
        data_type: numeric
        description: "Longitude of crime location."

      - name: point_y
        data_type: numeric
        description: "Latitude of crime location. "

      - name: lat
        data_type: numeric
        description: "Latitude of crime location. "
        
      - name: lng
        data_type: numeric
        description: "Longitude of crime location. "

      
        